<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\MediaDownloader.Application.csproj" />
    <ProjectReference Include="..\Domain\MediaDownloader.Domain.csproj" />
  </ItemGroup>

</Project>
